spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/robo
    username: robo
    password: robo_pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080


